# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  FinalRayTracing_config = debug

else ifeq ($(config),release)
  FinalRayTracing_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := FinalRayTracing

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

FinalRayTracing:
ifneq (,$(FinalRayTracing_config))
	@echo "==== Building FinalRayTracing ($(FinalRayTracing_config)) ===="
	@${MAKE} --no-print-directory -C . -f FinalRayTracing.make config=$(FinalRayTracing_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f FinalRayTracing.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FinalRayTracing"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"